google.maps.__gjsload__('infowindow', function(_){var VQa=function(a,b){if(a.mh.size===1){let c=Array.from(a.mh.values())[0];c.Vr!==b.Vr&&(c.set("map",null),a.mh.delete(c))}a.mh.add(b)},XQa=function(a,b,c=!1){var d=a.__gm;a=d.get("panes");d=d.get("innerContainer");b={Fm:a,Mj:_.zC.Mj(),Vy:d,shouldFocus:b,Vr:c};return new WQa(b)},mP=function(a,b){a.container.style.visibility=b?"":"hidden";b&&a.shouldFocus&&(a.focus(),a.shouldFocus=!1);b?YQa(a):a.xh=!1},ZQa=function(a){a.Fj.setAttribute("aria-labelledby",a.ph.id)},$Qa=function(a){var b=!!a.get("open"),
c=a.get("content");c=b?c:null;if(c===a.rh)mP(a,b&&a.get("position"));else{if(a.rh){let d=a.rh.parentNode;d===a.mh&&d.removeChild(a.rh)}c&&(a.wh=!1,a.mh.appendChild(c));mP(a,b&&a.get("position"));a.rh=c;nP(a)}},oP=function(a){var b=!!a.get("open"),c=a.get("headerContent"),d=!!a.get("ariaLabel"),e=a.get("headerDisabled"),f=!!a.get("isPoi"),g=!e;b=b?c:null;c=f&&e;a.Fj.style.paddingTop=!f&&e?"12px":"0";e=a.Fj;c?_.nx(e,"gm-style-iw-poi"):_.hJ(e,"gm-style-iw-poi");_.Gq.mh&&!_.Gq.sh&&(a.mh.style.overflow=
c?"auto":"scroll");b===a.sh?a.oh.style.display=g?"":"none":(a.sh&&(e=a.sh.parentNode,e===a.ph&&e.removeChild(a.sh)),b&&(a.wh=!1,a.ph.appendChild(b),g&&!d&&ZQa(a)),a.oh.style.display=g?"":"none",a.sh=b,nP(a))},nP=function(a){var b=a.getSize();if(b){var c=b.wn;b=b.minWidth;a.Fj.style.maxWidth=_.Jm(c.width);a.Fj.style.maxHeight=_.Jm(c.height);a.Fj.style.minWidth=_.Jm(b);b=!!a.get("headerDisabled");b=!!a.get("isPoi")&&b;a.mh.style.maxHeight=_.Gq.mh?_.Jm(c.height-(b?0:18)):_.Jm(c.height-(b?0:36));pP(a);
a.uh.start()}},aRa=function(a){var b=a.get("pixelOffset")||new _.Uo(0,0),c=new _.Uo(a.Fj.offsetWidth,a.Fj.offsetHeight);a=-b.height+c.height+11+60;var d=b.height+60,e=-b.width+c.width/2+60;c=b.width+c.width/2+60;b.height<0&&(d-=b.height);return{top:a,bottom:d,left:e,right:c}},YQa=function(a){!a.xh&&a.get("open")&&a.get("visible")&&a.get("position")&&(_.co(a,"visible"),a.xh=!0)},pP=function(a){var b=a.get("position");if(b&&a.get("pixelOffset")){var c=aRa(a);let d=b.x-c.left,e=b.y-c.top,f=b.x+c.right;
c=b.y+c.bottom;_.sx(a.anchor,b);b=a.get("zIndex");_.ux(a.container,_.Am(b)?b:e+60);a.set("pixelBounds",_.wp(d,e,f,c))}},cRa=function(a,b,c){return b instanceof _.wo?new bRa(a,b,c):new bRa(a,b)},eRa=function(a){a.mh&&a.cj.push(_.$n(a.mh,"pixelposition_changed",()=>{dRa(a)}))},dRa=function(a){var b=a.model.get("pixelPosition")||a.mh&&a.mh.get("pixelPosition");a.ph.set("position",b)},gRa=function(a){a=a.__gm;a.get("IW_AUTO_CLOSER")||a.set("IW_AUTO_CLOSER",new fRa);return a.get("IW_AUTO_CLOSER")},fRa=
class{constructor(){this.mh=new Set}};var WQa=class extends _.ho{constructor(a){super();this.rh=this.sh=this.th=null;this.xh=this.wh=!1;this.Vy=a.Vy;this.shouldFocus=a.shouldFocus;this.container=document.createElement("div");this.container.style.cursor="default";this.container.style.position="absolute";this.container.style.left=this.container.style.top="0";a.Fm.floatPane.appendChild(this.container);this.anchor=document.createElement("div");this.container.appendChild(this.anchor);this.qh=document.createElement("div");this.anchor.appendChild(this.qh);
this.Fj=document.createElement("div");this.qh.appendChild(this.Fj);this.Fj.setAttribute("role","dialog");this.Fj.tabIndex=-1;this.oh=document.createElement("div");this.Fj.appendChild(this.oh);this.ph=document.createElement("div");this.oh.appendChild(this.ph);this.zh=document.createElement("div");this.qh.appendChild(this.zh);this.mh=document.createElement("div");this.Fj.appendChild(this.mh);_.HHa(this.container);_.nx(this.Fj,"gm-style-iw");_.nx(this.anchor,"gm-style-iw-a");_.nx(this.qh,"gm-style-iw-t");
_.nx(this.zh,"gm-style-iw-tc");_.nx(this.Fj,"gm-style-iw-c");_.nx(this.oh,"gm-style-iw-chr");_.nx(this.ph,"gm-style-iw-ch");_.nx(this.mh,"gm-style-iw-d");this.set("isPoi",a.Vr);this.ph.setAttribute("id",_.vo());_.Gq.mh&&!_.Gq.sh&&(this.Fj.style.paddingInlineEnd="0",this.Fj.style.paddingBottom="0",this.mh.style.overflow="scroll");mP(this,!1);_.Wn(this.container,"mousedown",_.Mn);_.Wn(this.container,"mouseup",_.Mn);_.Wn(this.container,"mousemove",_.Mn);_.Wn(this.container,"pointerdown",_.Mn);_.Wn(this.container,
"pointerup",_.Mn);_.Wn(this.container,"pointermove",_.Mn);_.Wn(this.container,"dblclick",_.Mn);_.Wn(this.container,"click",_.Mn);_.Wn(this.container,"touchstart",_.Mn);_.Wn(this.container,"touchend",_.Mn);_.Wn(this.container,"touchmove",_.Mn);_.ex(this.container,"contextmenu",this,this.Ah);_.ex(this.container,"wheel",this,_.Mn);a=new _.Qo(12,12);var b=new _.Uo(24,24);this.nh=new _.Pr({Tr:a,qt:b,offset:new _.Qo(-6,-6),RD:!0,ownerElement:this.oh});this.oh.appendChild(this.nh.element);_.Wn(this.nh.element,
"click",c=>{_.Mn(c);_.co(this,"closeclick");this.set("open",!1)});this.uh=new _.tq(()=>{!this.wh&&this.get("content")&&this.get("visible")&&(_.co(this,"domready"),this.wh=!0)},0);this.yh=_.Wn(this.container,"keydown",c=>{c.key!=="Escape"&&c.key!=="Esc"||!this.Fj.contains(document.activeElement)||(c.stopPropagation(),_.co(this,"closeclick"),this.set("open",!1))})}ariaLabel_changed(){var a=this.get("ariaLabel");a?this.Fj.setAttribute("aria-label",a):(this.Fj.removeAttribute("aria-label"),this.get("headerDisabled")||
ZQa(this))}open_changed(){$Qa(this);oP(this)}headerContent_changed(){oP(this)}headerDisabled_changed(){oP(this)}content_changed(){$Qa(this)}pendingFocus_changed(){this.get("pendingFocus")&&(this.get("open")&&this.get("visible")&&this.get("position")?_.Nq(this.Fj,!0):console.warn("Setting focus on InfoWindow was ignored. This is most likely due to InfoWindow not being visible yet."),this.set("pendingFocus",!1))}dispose(){setTimeout(()=>{document.activeElement&&document.activeElement!==document.body||
(this.th&&this.th!==document.body?_.Nq(this.th,!0)||_.Nq(this.Vy,!0):_.Nq(this.Vy,!0))});this.yh&&_.Qn(this.yh);this.container.parentNode.removeChild(this.container);this.uh.stop();this.uh.dispose()}getSize(){var a=this.get("layoutPixelBounds"),b=this.get("pixelOffset"),c=this.get("maxWidth")||648,d=this.get("minWidth")||0;if(!b)return null;a?(b=a.maxY-a.minY-(11+-b.height),a=a.maxX-a.minX-6,a>=240&&(a-=120),b>=240&&(b-=120)):(a=648,b=654);a=Math.min(a,c);a=Math.max(d,a);a=Math.max(0,a);b=Math.max(0,
b);return{wn:new _.Uo(a,b),minWidth:d}}pixelOffset_changed(){var a=this.get("pixelOffset")||new _.Uo(0,0);this.qh.style.right=_.Jm(-a.width);this.qh.style.bottom=_.Jm(-a.height+11);nP(this)}layoutPixelBounds_changed(){nP(this)}position_changed(){this.get("position")?(pP(this),mP(this,!!this.get("open"))):mP(this,!1)}zIndex_changed(){pP(this)}visible_changed(){this.container.style.display=this.get("visible")?"":"none";this.uh.start();if(this.get("visible")){let a=this.nh.element.style.display;this.nh.element.style.display=
"none";this.nh.element.getBoundingClientRect();this.nh.element.style.display=a;YQa(this)}else this.xh=!1}Ah(a){for(var b=!1,c=this.get("content"),d=a.target;!b&&d;)b=d===c,d=d.parentNode;b?_.Gn(a):_.In(a)}focus(){this.th=document.activeElement;var a;_.Gq.wh&&(a=this.mh.getBoundingClientRect());if(this.get("disableAutoPan"))_.Nq(this.Fj,!0);else{var b=_.yx(this.mh);if(b.length){b=b[0];a=a||this.mh.getBoundingClientRect();var c=b.getBoundingClientRect();_.Nq(c.bottom<=a.bottom&&c.right<=a.right?b:this.Fj,
!0)}else _.Nq(this.nh.element,!0)}}};var bRa=class{constructor(a,b,c){this.model=a;this.isOpen=!0;this.mh=this.oh=this.Mh=null;this.cj=[];var d=a.get("shouldFocus");this.ph=XQa(b,d,a.Vr);var e=b.__gm;(d=b instanceof _.wo)&&c?c.then(h=>{this.isOpen&&(this.Mh=h,this.mh=new _.cN(k=>{this.oh=new _.WB(b,h,k,()=>{});h.Ej(this.oh);return this.oh}),this.mh.bindTo("latLngPosition",a,"position"),eRa(this))}):(this.mh=new _.cN,this.mh.bindTo("latLngPosition",a,"position"),this.mh.bindTo("center",e,"projectionCenterQ"),this.mh.bindTo("zoom",e),
this.mh.bindTo("offset",e),this.mh.bindTo("projection",b),this.mh.bindTo("focus",b,"position"),eRa(this));this.qh=d?a.infoWindow.get("logAsInternal")?148284:148285:null;var f=new _.TM(["scale"],"visible",h=>h==null||h>=.3);this.mh&&f.bindTo("scale",this.mh);var g=this.ph;g.set("logAsInternal",!!a.infoWindow.get("logAsInternal"));g.bindTo("ariaLabel",a);g.bindTo("zIndex",a);g.bindTo("layoutPixelBounds",e,"pixelBounds");g.bindTo("disableAutoPan",a);g.bindTo("pendingFocus",a);g.bindTo("maxWidth",a);
g.bindTo("minWidth",a);g.bindTo("content",a);g.bindTo("headerContent",a);g.bindTo("headerDisabled",a);g.bindTo("pixelOffset",a);g.bindTo("visible",f);this.nh=new _.tq(()=>{if(b instanceof _.wo)if(this.Mh){var h=a.get("position");h&&_.Xla(b,this.Mh,new _.Do(h),aRa(g))}else c.then(()=>{this.nh.start()});else(h=g.get("pixelBounds"))?_.co(e,"pantobounds",h):this.nh.start()},150);if(d){let h=null;this.cj.push(_.$n(a,"position_changed",()=>{var k=a.get("position");!k||a.get("disableAutoPan")||k.equals(h)||
(this.nh.start(),h=k)}))}else a.get("disableAutoPan")||this.nh.start();g.set("open",!0);this.cj.push(_.On(g,"domready",()=>{a.trigger("domready")}));this.cj.push(_.On(g,"visible",()=>{a.trigger("visible")}));this.cj.push(_.On(g,"closeclick",()=>{a.close();a.trigger("closeclick")}));this.cj.push(_.$n(a,"pixelposition_changed",()=>{dRa(this)}));this.qh&&_.P(b,this.qh)}close(){if(this.isOpen){this.isOpen=!1;this.model.trigger("close");for(var a of this.cj)_.Qn(a);this.cj.length=0;this.nh.stop();this.nh.dispose();
this.Mh&&this.oh&&this.Mh.Vl(this.oh);a=this.ph;a.unbindAll();a.set("open",!1);a.dispose();this.mh&&this.mh.unbindAll()}}};_.bm("infowindow",{EJ:function(a){var b=null;_.$n(a,"map_changed",function d(){var e=a.get("map");b&&(b.sF.mh.delete(a),b.vN.close(),b=null);if(e){let f=e.__gm;f.get("panes")?f.get("innerContainer")?(b={vN:cRa(a,e,e instanceof _.wo?f.nh.then(({Mh:g})=>g):void 0),sF:gRa(e)},VQa(b.sF,a)):_.Zn(f,"innercontainer_changed",d):_.Zn(f,"panes_changed",d)}})}});});
